apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdn-secret-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-130695a7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdn-secret
  namespace: infra
spec:
  storageClassName: efs-sc
  volumeName: cdn-secret-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
