## Edge and Mid cache tier
apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: infra
spec:
  selector:
    func: cache
    role: edge
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-edge-tier
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: cache
      role: edge
  template:
    metadata:
      labels:
        func: cache
        role: edge
    spec:
      hostname: edge
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: edge-tier
        image: cdn-edge:latest
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: mid
  namespace: infra
spec:
  selector:
    func: cache
    role: mid
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-mid-tier
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: cache
      role: mid
  template:
    metadata:
      labels:
        func: cache
        role: mid
    spec:
      hostname: mid
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: mid-tier
        image: cdn-mid:latest
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
## 2 DBs: for influxdb: traffic stats, and for db: traffic operations
apiVersion: v1
kind: Service
metadata:
  name: influxdb 
  namespace: infra
spec:
  selector:
    func: db
    role: stat
  ports:
    - port: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-stat-db
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: db
      role: stat
  template:
    metadata:
      labels:
        func: db
        role: stat
    spec:
      hostname: influxdb
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: stat-db
        image: cdn-stat-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: db 
  namespace: infra
spec:
  selector:
    func: db
    role: ops
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops-db
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: db
      role: ops
  template:
    metadata:
      labels:
        func: db
        role: ops
    spec:
      hostname: db
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: postgres-data
        emptyDir: {}
      containers:
      - name: ops-db
        image: cdn-ops-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
        envFrom:
          - configMapRef:
              name: cdn-config
---
## Enroller
apiVersion: v1
kind: Service
metadata:
  name: enroller
  namespace: infra
spec:
  selector:
    func: enroll
## somehow no port exposing in docker-compose file
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-enroller
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: enroll
  template:
    metadata:
      labels:
        func: enroll
    spec:
      hostname: enroller
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: enroller
        image: cdn-enroller:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
#vault: create credentials
apiVersion: v1
kind: Service
metadata:
  name: trafficvault
  namespace: infra
spec:
  selector:
    func: secret
## not sure what these ports for..
  ports:
    - name: port0
      port: 8088
    - name: port1
      port: 8087
    - name: port2
      port: 8098
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-traffic-vault
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: secret
  template:
    metadata:
      labels:
        func: secret
    spec:
      hostname: trafficvault
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: schema
        persistentVolumeClaim:
          claimName: cdn-schemas
      containers:
      - name: vault
        image: cdn-vault:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8087
        - containerPort: 8088
        - containerPort: 8098
        env:
        - name: CLUSTER_NAME
          value: trafficvault
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /etc/riak/schemas
            name: schema
        envFrom:
          - configMapRef:
              name: cdn-config
---
#statistic manager: no expose service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-stats
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: stats
  template:
    metadata:
      labels:
        func: stats
    spec:
      hostname: trafficstats
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: stats
        image: cdn-stats:latest
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
#operation(API) servers: Go and Static
apiVersion: v1
kind: Service
metadata:
  name: trafficops
  namespace: infra
spec:
  selector:
    func: ops
    lang: go
  ports:
    - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-ops
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ops
      lang: go
  template:
    metadata:
      labels:
        func: ops
        lang: go
    spec:
      hostname: trafficops
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: ops-go
        image: cdn-ops:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
#### TODO: add static app here
---
#Router
apiVersion: v1
kind: Service
metadata:
  name: trafficrouter
  namespace: infra
spec:
  selector:
    func: router
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
    - name: dns-udp
      protocol: UDP
      port: 53
    - name: port1
      port: 80
    - name: port2
      port: 443
    - name: port3
      port: 3333
    - name: port4
      port: 3443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-router
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: router
  template:
    metadata:
      labels:
        func: router
    spec:
      hostname: trafficrouter
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: router
        image: cdn-router:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
        - containerPort: 3443
        - containerPort: 443
        - containerPort: 53
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
#Monitor
apiVersion: v1
kind: Service
metadata:
  name: trafficmonitor
  namespace: infra
spec:
  selector:
    func: monitor
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-monitor
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: monitor
  template:
    metadata:
      labels:
        func: monitor
    spec:
      hostname: trafficmonitor
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: router
        image: cdn-monitor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
#Mock origin server
apiVersion: v1
kind: Service
metadata:
  name: origin
  namespace: infra
spec:
  selector:
    func: data-server
  ports:
    - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-server
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: data-server
  template:
    metadata:
      labels:
        func: data-server
    spec:
      hostname: origin
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      - name: content-dir
        persistentVolumeClaim:
          claimName: cdn-content
      containers:
      - name: data-server
        image: cdn-exp-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
          - mountPath: /var/www/html
            name: content-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Pod
metadata:
  name: cdn-client
  namespace: infra
spec:
  hostname: client
  volumes:
  - name: secret-dir
    persistentVolumeClaim:
      claimName: cdn-secret
  containers:
  - name: client
    image: tc-client
    imagePullPolicy: Never
    volumeMounts:
      - mountPath: /shared
        name: secret-dir
    envFrom:
      - configMapRef:
          name: cdn-config
---
### TODO: add cdn-smtp
