## Edge and Mid cache tier
apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: infra
spec:
  selector:
    func: cache
    role: edge
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-edge
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: cache
      role: edge
  template:
    metadata:
      labels:
        func: cache
        role: edge
    spec:
      hostname: edge
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: edge-tier
        image: public.ecr.aws/d7k3x9e1/cdn-edge:v1
        env:
        - name: MY_HOSTNAME
          value: "edge"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: mid-01
  namespace: infra
spec:
  selector:
    func: cache
    role: mid
    number: one
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-mid-01
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: cache
      role: mid
      number: one
  template:
    metadata:
      labels:
        func: cache
        role: mid
        number: one
    spec:
      hostname: mid-01
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: mid-tier
        image: public.ecr.aws/d7k3x9e1/cdn-mid:v1
        env:
        - name: MY_HOSTNAME
          value: "mid-01"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: mid-02
  namespace: infra
spec:
  selector:
    func: cache
    role: mid
    number: two
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-mid-02
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: cache
      role: mid
      number: two
  template:
    metadata:
      labels:
        func: cache
        role: mid
        number: two
    spec:
      hostname: mid-02
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: mid-tier
        image: public.ecr.aws/d7k3x9e1/cdn-mid:v1
        env:
        - name: MY_HOSTNAME
          value: "mid-02"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
---
#Mock origin server
apiVersion: v1
kind: Service
metadata:
  name: origin
  namespace: infra
spec:
  selector:
    func: data-server
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-server
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      func: data-server
  template:
    metadata:
      labels:
        func: data-server
    spec:
      hostname: origin
      volumes:
      - name: secret-dir
        persistentVolumeClaim:
          claimName: cdn-secret
      containers:
      - name: data-server
        image: public.ecr.aws/d7k3x9e1/app-server:v1
        env:
        - name: MY_HOSTNAME
          value: "origin"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /shared
            name: secret-dir
        envFrom:
          - configMapRef:
              name: cdn-config
